networks:
  homelab:
    external: true
  homelab_vlan:
    external: true

include:
  - common/docker-compose-unbound.yaml
  - pi-5/docker-compose-ad-blocker.yaml
  - pi-5/docker-compose-ai-automation.yaml
  - pi-5/docker-compose-arr.yaml
  - pi-5/docker-compose-auth.yaml
  - pi-5/docker-compose-monitoring.yaml
  - pi-5/docker-compose-utils.yaml
  - pi-5/docker-compose-reverse-proxy.yaml
  - pi-5/docker-compose-immich.yaml

services:
  homepage:
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
      PORT: 80
      LOG_LEVEL: info
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICES_ROOT}/homepage/config:/app/config:rw
      - /mnt/Movies:/mnt/Movies:ro
      - /mnt/Series:/mnt/Series:ro
    expose:
      - 80
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.200
      homelab:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage-secure.loadbalancer.server.port=80"
