networks:
  homelab:
    external: true
  homelab_vlan:
    external: true
  homelab_dns:
    external: true

include:
  - common/docker-compose-unbound.yaml

services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      unbound:
        condition: service_healthy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
      PIHOLE_UID: ${PUID}
      PIHOLE_GID: ${PGID}
      TAIL_FTL_LOG: 1
      FTLCONF_dns_upstreams: 172.20.0.5#5335
      FTLCONF_dns_cache_size: ${DNS_CACHE_SIZE}
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_dns_listeningMode: ${DNS_LISTENING_MODE}
      FTLCONF_ntp_ipv4_active: ${NTP_IPV4_ACTIVE:-false}
      FTLCONF_ntp_ipv6_active: ${NTP_IPV6_ACTIVE:-false}
      FTLCONF_ntp_sync_active: ${NTP_IPV6_ACTIVE:-false}
    volumes:
      - ${SERVICES_ROOT}/etc-pihole:/etc/pihole
    cap_add:
      - SYS_NICE
      - NET_BIND_SERVICE
    privileged: true
    restart: unless-stopped
    networks:
      - homelab

  portainer-agent:
    hostname: portainer-agent
    container_name: portainer_agent
    image: portainer/agent:latest
    restart: always
    environment:
      LOG_LEVEL: INFO
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - homelab
