services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "5353:80/tcp"
    environment:
      TZ: America/Argentina/Buenos_Aires
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    env_file:
      - .env
  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
