services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "5353:80/tcp"
    environment:
      TZ: $TZ
      WEBPASSWORD: PIHOLE_WEBPASSWORD
    # Volumes store your data between container upgrades
    volumes:
      - /docker/pihole/etc-pihole:/etc/pihole
      - /docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    env_file: .env

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=$TZ
      - PLEX_CLAIM=$PLEX_CLAIM
    hostname: plex
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tmp:/transcode
      - $SERIES:/data/tv
      - $MOVIES:/data/movies
