networks:
  homelab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1

services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
      PIHOLE_UID: ${PUID}
      PIHOLE_GID: ${PGID}
      TAIL_FTL_LOG: 1
      FTLCONF_dns_upstreams: 172.25.0.28#5335
      FTLCONF_dns_cache_size: ${DNS_CACHE_SIZE}
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_dns_listeningMode: ${DNS_LISTENING_MODE}
      FTLCONF_ntp_ipv4_active: ${NTP_IPV4_ACTIVE:-false}
      FTLCONF_ntp_ipv6_active: ${NTP_IPV6_ACTIVE:-false}
      FTLCONF_ntp_sync_active: ${NTP_IPV6_ACTIVE:-false}
    volumes:
      - ${SERVICES_ROOT}/etc-pihole:/etc/pihole
    cap_add:
      - SYS_NICE
    privileged: true
    restart: unless-stopped
    networks:
      - homelab
