networks:
  homelab:
    external: true
  homelab_vlan:
    external: true

include:
  - common/docker-compose-unbound.yaml
  - rpi-5/docker-compose-ad-blocker.yaml
  - rpi-5/docker-compose-ai-automation.yaml
  - rpi-5/docker-compose-arr.yaml
  - rpi-5/docker-compose-auth.yaml
  - rpi-5/docker-compose-monitoring.yaml
  - rpi-5/docker-compose-utils.yaml

services:
  homepage:
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PORT: 80
      LOG_LEVEL: info
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - ${SERVICES_ROOT}/homepage/config:/app/config:rw
      - /mnt/Movies:/mnt/Movies:ro
      - /mnt/Series:/mnt/Series:ro
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.200
      homelab:
