networks:
  homelab:
    external: true
  homelab_vlan:
    external: true
  homelab_dns:
    external: true
  no-internet:
    external: true

include:
  - services/docker-compose-ad-blocker.yaml
  - services/docker-compose-arr.yaml
  - services/docker-compose-monitoring.yaml
  - services/docker-compose-utils.yaml
  - services/docker-compose-reverse-proxy.yaml
  - services/docker-compose-immich.yaml
  - services/docker-compose-searx.yaml
  # - services/docker-compose-office.yaml
  # - services/docker-compose-ai-automation.yaml

services:
  homepage:
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      PORT: 80
      LOG_LEVEL: ${LOG_LEVEL:-info}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - ${SERVICES_ROOT}/homepage/config:/app/config:rw
      - ${MOVIES}:${MOVIES}:ro
      - ${SERIES}:${SERIES}:ro
      - ${IMMICH}:${IMMICH}:ro
      - ./img/doge.ico:/app/public/doge.ico:ro
    expose:
      - 80
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.200
      homelab:
      no-internet:
      homelab_dns:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage-secure.loadbalancer.server.port=80"
    profiles: [ rpi5 ]
