networks:
  homelab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
  homelab_vlan:
    driver_opts:
      parent: eth0
    ipam:
      driver: macvlan
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1

include:
  - common/docker-compose-unbound.yaml
  - rpi-5/docker-compose-ad-blocker.yaml
  - rpi-5/docker-compose-ai-automation.yaml
  - rpi-5/docker-compose-arr.yaml
  - rpi-5/docker-compose-auth.yaml
  - rpi-5/docker-compose-monitoring.yaml
  - rpi-5/docker-compose-utils.yaml

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICES_ROOT}/portainer:/data
    networks:
      - homelab

  samba:
    image: dockurr/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      NAME: Media
      USER: ${USERNAME}
      PASS: ${PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt:/storage
    networks:
      - homelab
