networks:
  homelab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1

services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      TZ: ${TZ}
      PIHOLE_UID: ${PUID}
      PIHOLE_GID: ${PGID}
      TAIL_FTL_LOG: 1
      FTLCONF_dns_upstreams: 127.0.0.1#5335
      FTLCONF_dns_cache_size: ${DNS_CACHE_SIZE}
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_dns_listeningMode: ${DNS_LISTENING_MODE}
      FTLCONF_ntp_ipv4_active: ${NTP_IPV4_ACTIVE:-true}
      FTLCONF_ntp_ipv6_active: ${NTP_IPV6_ACTIVE:-true}
      FTLCONF_ntp_sync_active: ${NTP_IPV6_ACTIVE:-true}
    volumes:
      - ${SERVICES_ROOT}/etc-pihole:/etc/pihole
    cap_add:
      - SYS_NICE
    privileged: true
    restart: unless-stopped
    networks:
      - homelab

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest # Change to use 'mvance/unbound-rpi:latest' on raspberry pi
    # use pihole network stack
    network_mode: service:pihole
    volumes:
      # main config
      - ${SERVICES_ROOT}/unbound/config/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      # custom config (unbound.conf.d/your-config.conf). unbound.conf includes these via wilcard include
      - ${SERVICES_ROOT}/unbound/config/unbound.conf.d:/opt/unbound/etc/unbound/unbound.conf.d:ro
      # log file
      - ${SERVICES_ROOT}/unbound/logs/unbound.log:/opt/unbound/etc/unbound/unbound.log
    restart: unless-stopped
    post_start:
      # remove unused config files
      - command: rm -f /opt/unbound/etc/unbound/a-records.conf
      - command: rm -f /opt/unbound/etc/unbound/forward-records.conf
      - command: rm -f /opt/unbound/etc/unbound/srv-records.conf
