networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    expose:
      - 9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SERVICES_ROOT}/portainer:/data
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9443"
    profiles: [ rpi5 ]

  portainer-agent:
    hostname: portainer-agent
    container_name: portainer_agent
    image: portainer/agent:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: INFO
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - homelab
    profiles: [ rpi2w ]

  samba:
    hostname: samba
    image: dockurr/samba:latest
    container_name: samba
    restart: always
    environment:
      NAME: Media
      USER: ${USERNAME}
      PASS: ${PASSWORD}
      UID: ${PUID}
      GID: ${PGID}
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt:/storage
    networks:
      - homelab
    profiles: [ rpi5 ]

  code-server:
    hostname: code-server
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      PASSWORD: ${PASSWORD}
      PWA_APPNAME: Compumundo
    volumes:
      - ~/Documents:/workspace
      - ${SERVICES_ROOT}/code-server/config:/config
    expose:
      - 8443
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.code.entrypoints=http"
      - "traefik.http.routers.code-secure.rule=Host(`code.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.code-secure.entrypoints=https"
      - "traefik.http.routers.code-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.code-secure.loadbalancer.server.port=8443"
    profiles: [ rpi5 ]

  vaultwarden:
    hostname: vaultwarden
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://vaultwarden.local.${DOMAIN_NAME}"
    volumes:
      - ${SERVICES_ROOT}/vaultwarden/:/data/
    expose:
      - 80
    restart: unless-stopped
    networks:
      - no-internet
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=no-internet"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=http"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`vaultwarden.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
      - "traefik.http.routers.vaultwarden-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.vaultwarden-secure.loadbalancer.server.port=80"
    profiles: [ rpi5 ]

  juice-shop:
    hostname: juice-shop
    image: bkimminich/juice-shop
    container_name: juice-shop
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - no-internet
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=no-internet"
      - "traefik.http.routers.juice-shop.rule=Host(`juice-shop.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.juice-shop.entrypoints=http"
      - "traefik.http.routers.juice-shop-secure.rule=Host(`juice-shop.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.juice-shop-secure.entrypoints=https"
      - "traefik.http.routers.juice-shop-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.juice-shop-secure.loadbalancer.server.port=3000"
    profiles: [ rpi5 ]
