networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_TYPE: ${VPN_TYPE}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
    volumes:
      - ${SERVICES_ROOT}/gluetun:/gluetun
    expose:
      - 8080
      - 9091
      - 51413
      - 51413/udp
    networks:
      - homelab
      - homelab_dns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission-secure.rule=Host(`transmission.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.transmission-secure.loadbalancer.server.port=9091"
    profiles: [ rpi5 ]

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      USER: ${USERNAME}
      PASS: ${PASSWORD}
    volumes:
      - ${SERVICES_ROOT}/transmission/data:/config
      - /mnt:/downloads
    network_mode: "service:gluetun"
#    expose: # Exposed in gluetun: 9091, 51413, 51413/udp
    profiles: [ rpi5 ]

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    hostname: flaresolverr
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LANG: en_GB
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ${SERVICES_ROOT}/flaresolverr:/config
    expose:
      - 8191
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.flaresolverr.entrypoints=http"
      - "traefik.http.routers.flaresolverr-secure.rule=Host(`flaresolverr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.flaresolverr-secure.entrypoints=https"
      - "traefik.http.routers.flaresolverr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.flaresolverr-secure.loadbalancer.server.port=8191"
    profiles: [ rpi5 ]

  jackett:
    image: linuxserver/jackett:latest
    hostname: jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      AUTO_UPDATE: false
    volumes:
      - /mnt:/downloads
      - ${SERVICES_ROOT}/Jackett:/config
    expose:
      - 9117
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.routers.jackett-secure.rule=Host(`jackett.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett-secure.entrypoints=https"
      - "traefik.http.routers.jackett-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.jackett-secure.loadbalancer.server.port=9117"
    profiles: [ rpi5 ]

  sonarr:
    image: linuxserver/sonarr:latest
    hostname: sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt:/downloads
      - ${SERIES}/Series:/tv
      - ${SERVICES_ROOT}/Sonarr:/config
    expose:
      - 8989
    depends_on: [ transmission, jackett, prowlarr ]
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.sonarr-secure.loadbalancer.server.port=8989"
    profiles: [ rpi5 ]

  radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt:/downloads
      - ${MOVIES}/Movies:/movies
      - ${SERVICES_ROOT}/radarr/config:/config
    expose:
      - 7878
    depends_on: [ transmission, jackett, prowlarr ]
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.radarr-secure.loadbalancer.server.port=7878"
    profiles: [ rpi5 ]

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    hostname: prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/prowlarr:/config
    expose:
      - 9696
    depends_on: [ flaresolverr, transmission ]
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prowlarr.entrypoints=http"
      - "traefik.http.routers.prowlarr-secure.rule=Host(`prowlarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prowlarr-secure.entrypoints=https"
      - "traefik.http.routers.prowlarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.prowlarr-secure.loadbalancer.server.port=9696"
    profiles: [ rpi5 ]

  bazarr:
    image: linuxserver/bazarr:latest
    hostname: bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt/Series/Series:/tv
      - /mnt/Movies/Movies:/movies
      - ${SERVICES_ROOT}/Bazarr:/config
    expose:
      - 6767
    depends_on: [ sonarr, radarr ]
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.bazarr.entrypoints=http"
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.bazarr-secure.entrypoints=https"
      - "traefik.http.routers.bazarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.bazarr-secure.loadbalancer.server.port=6767"
    profiles: [ rpi5 ]

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    hostname: overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/Overseerr:/config
    expose:
      - 5055
    depends_on: [ sonarr, radarr, bazarr, plex ]
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.overseerr.entrypoints=http"
      - "traefik.http.routers.overseerr-secure.rule=Host(`overseerr.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.overseerr-secure.entrypoints=https"
      - "traefik.http.routers.overseerr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.overseerr-secure.loadbalancer.server.port=5055"
    profiles: [ rpi5 ]

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: plex-server-home
    environment:
      TZ: ${TZ}
      ALLOWED_NETWORKS: 192.168.1.0/24,172.25.0.0/24
    volumes:
      - ${SERVICES_ROOT}/plex/config:/config
      - ${SERVICES_ROOT}/plex/transcode:/transcode
      - /mnt/Movies/Movies:/movies
      - /mnt/Series/Series:/tv
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.254
      homelab:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex.entrypoints=http"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.plex-secure.loadbalancer.server.port=32400"
    profiles: [ rpi5 ]
