networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: plex-server-home
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: ${TZ}
      ALLOWED_NETWORKS: 192.168.1.0/24,172.25.0.0/24
    volumes:
      - ${SERVICES_ROOT}/plex/config:/config
      - ${SERVICES_ROOT}/plex/transcode:/transcode
      - /mnt/Movies/Movies:/movies
      - /mnt/Series/Series:/tv
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.254
      homelab:

  gluetun:
    image: qmcgaw/gluetun
    hostname: gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${SERVICES_ROOT}/gluetun:/gluetun
    ports:
      # Transmission
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      # Flaresolverr
      - 8191:8191
      # Jackett
      - 9117:9117
      # Sonarr
      - 8989:8989
      # Radarr
      - 7878:7878
      # Prowlarr
      - 9696:9696
      # Bazarr
      - 6767:6767
      # Overseerr
      - 5055:5055
    environment:
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      OPENVPN_USER: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      SERVER_COUNTRIES: ${NORDVPN_COUNTRY}
    networks:
      - homelab

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      USER: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${SERVICES_ROOT}/transmission:/config
      - /mnt:/data
    network_mode: service:gluetun

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    hostname: flaresolverr
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LANG: en_GB
      LOG_LEVEL: DEBUG
    volumes:
      - ${SERVICES_ROOT}/flaresolverr:/config
    network_mode: service:gluetun

  jackett:
    image: linuxserver/jackett:latest
    hostname: jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      AUTO_UPDATE: true
    volumes:
      - /mnt:/downloads
      - ${SERVICES_ROOT}/Jackett:/config
    network_mode: service:gluetun

  sonarr:
    image: linuxserver/sonarr:latest
    hostname: sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt:/downloads
      - /mnt/Series/Series:/tv
      - ${SERVICES_ROOT}/Sonarr:/config
    depends_on: [ transmission, jackett, prowlarr ]
    networks:
      - homelab

  radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt:/downloads
      - /mnt/Movies/Movies:/movies
      - ${SERVICES_ROOT}/radarr/config:/config
    depends_on: [ transmission, jackett, prowlarr ]
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    hostname: prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/prowlarr:/config
    depends_on: [ flaresolverr, transmission ]
    network_mode: service:gluetun

  bazarr:
    image: linuxserver/bazarr:latest
    hostname: bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt/Series/Series:/tv
      - /mnt/Movies/Movies:/movies
      - ${SERVICES_ROOT}/Bazarr:/config
    depends_on: [ sonarr, radarr ]
    network_mode: service:gluetun

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    hostname: overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/Overseerr:/config
    depends_on: [ sonarr, radarr, bazarr, plex ]
    network_mode: service:gluetun
