networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

name: AdGuard Home and Sync

services:
  adguardhome:
    hostname: adguardhome
    container_name: adguardhome
    image: adguard/adguardhome:latest
    depends_on:
      unbound:
        condition: service_healthy
    user: "${PUID}:${PGID}"
#    ports:
#      # Plain DNS
#      - 53:53/tcp
#      - 53:53/udp
#      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
#      - 80:80/tcp
#      - 443:443/tcp
#      - 443:443/udp
#      - 2000:3000/tcp
#      # DNS-over-TLS
#      - 853:853/tcp
    volumes:
      - ${SERVICES_ROOT}/adguardhome/work:/opt/adguardhome/work
      - ${SERVICES_ROOT}/adguardhome/config:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.253
      homelab:


  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    user: "${PUID}:${PGID}"
    ports:
      - 8080:8080
    environment:
      TZ: ${TZ}
      LOG_LEVEL: info
      ORIGIN_URL: http://192.168.1.253
      ORIGIN_USERNAME: ${USERNAME}
      ORIGIN_PASSWORD: ${PASSWORD}
      CRON: "0 * 1 * *"
    volumes:
      - ${SERVICES_ROOT}/adguardhome-sync/config:/config
    depends_on: [ adguardhome ]
    restart: unless-stopped
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.252
      homelab:
