networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICES_ROOT}/portainer:/data
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"

  samba:
    hostname: samba
    image: dockurr/samba:latest
    container_name: samba
    restart: always
    environment:
      NAME: Media
      USER: ${USERNAME}
      PASS: ${PASSWORD}
      UID: ${PUID}
      GID: ${PGID}
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt:/storage
    networks:
      - homelab

  cloudflared:
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - homelab

  code-server:
    hostname: code-server
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      PASSWORD: ${PASSWORD}
      PWA_APPNAME: Compumundo
    volumes:
      - ~/Documents:/workspace
      - ${SERVICES_ROOT}/code-server/config:/config
    expose:
      - 8443
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.code.entrypoints=http"
      - "traefik.http.routers.code-secure.rule=Host(`code.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.code-secure.entrypoints=https"
      - "traefik.http.routers.code-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.code-secure.loadbalancer.server.port=8443"
