networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

name: Utility Services

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICES_ROOT}/portainer:/data
    networks:
      - homelab

  samba:
    hostname: samba
    image: dockurr/samba:latest
    container_name: samba
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      NAME: Media
      USER: ${USERNAME}
      PASS: ${PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt:/storage
    networks:
      - homelab

  cloudflared:
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - homelab

  code-server:
    hostname: code-server
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      PASSWORD: ${PASSWORD}
    volumes:
      - ~/Documents:/workspace
      - ${SERVICES_ROOT}/code-server/config:/config
    ports:
      - 5443:8443
    restart: unless-stopped
    networks:
      - homelab
