networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  homepage:
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PORT: 80
      LOG_LEVEL: info
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.200
    volumes:
      - ${SERVICES_ROOT}/homepage/config:/app/config:rw
      - /mnt/Movies:/mnt/Movies:ro
      - /mnt/Series:/mnt/Series:ro
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.200
      homelab:

  openvscode-server:
    hostname: openvscode-server
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/openvscode-server/config:/config
    ports:
      - 5000:3000
    restart: unless-stopped
    networks:
      - homelab

  cloudflared:
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - homelab

  duckdns:
    hostname: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      SUBDOMAINS: ${DUCK_DNS_SUBDOMAINS}
      TOKEN: ${DUCK_DNS_TOKEN}
    volumes:
      - ${SERVICES_ROOT}/duckdns/config:/config
    restart: unless-stopped
