networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICES_ROOT}/portainer:/data
    networks:
      - homelab

  samba:
    hostname: samba
    image: dockurr/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      NAME: Media
      USER: ${USERNAME}
      PASS: ${PASSWORD}
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt:/storage
    networks:
      - homelab

  openvscode-server:
    hostname: openvscode-server
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${SERVICES_ROOT}/openvscode-server/config:/config
      - ${SERVICES_ROOT}/openvscode-server/workspace:/workspace
    ports:
      - 5000:3000
    restart: unless-stopped
    networks:
      - homelab

  cloudflared:
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - homelab
