networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    restart: unless-stopped
    hostname: webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - 9191:8080/tcp
    volumes:
      - ${SERVICES_ROOT}/webui:/app/backend/data
    depends_on: [ ollama ]
    networks:
      - homelab

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    hostname: ollama
    ports:
      - 11434:11434/tcp
    volumes:
      - ${SERVICES_ROOT}/ollama/ollama:/root/.ollama
    networks:
      - homelab

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    hostname: n8n
    environment:
      TZ: ${TZ}
      GENERIC_TIMEZONE: ${TZ}
      N8N_SECURE_COOKIE: false
    ports:
      - 5678:5678
    volumes:
      - ${SERVICES_ROOT}/n8n:/home/node/.n8n
    networks:
      - homelab
