networks:
  homelab_vlan:
    external: true
  homelab:
    external: true

services:
  adguardhome:
    hostname: adguardhome
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      # Plain DNS
      - 53:53/tcp
      - 53:53/udp
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 2000:3000/tcp
      # DNS-over-TLS
      - 853:853/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICES_ROOT}/adguardhome/work:/opt/adguardhome/work
      - ${SERVICES_ROOT}/adguardhome/config:/opt/adguardhome/conf
    privileged: true
    restart: unless-stopped
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.253
      homelab:


  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      LOG_LEVEL: info
      ORIGIN_URL: http://192.168.1.253
      ORIGIN_USERNAME: ${USERNAME}
      ORIGIN_PASSWORD: ${PASSWORD}
      CRON: "0 * 1 * *"
    volumes:
      - ${SERVICES_ROOT}/adguardhome-sync/config:/config
    depends_on: [ adguardhome ]
    restart: unless-stopped
    networks:
      homelab_vlan:
        ipv4_address: 192.168.1.252
      homelab:


  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    network_mode: service:adguardhome
    volumes:
      - ./unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw
      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - ./unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw
      - ./unbound/iana.d/:/usr/local/unbound/iana.d/:rw
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    healthcheck:
      disable: true
    restart: unless-stopped
