networks:
  homelab:
    external: true
  homelab_dns:
    external: true

services:
  unbound:
    hostname: unbound
    container_name: unbound
    image: mvance/unbound-rpi:latest
    expose:
      - 53
    networks:
      homelab_dns:
        ipv4_address: 172.20.0.5
